#!/bin/bash
# Author: EarthlySkies <earthlyskies@protonmail.ch>
# Part of the Kura5 project's Linux integration suite
# A small script to uninstall Kura5 from /opt/kura5
# Requires root privileges

# Text formatting
BOLD=$(tput bold)
NORM=$(tput sgr0)

# We need this and Bash can't do return values
if [ -L "${BASH_SOURCE[0]}" ]; then
    LAUNCHERPATH=$(readlink "${BASH_SOURCE[0]}")
    LAUNCHERPATH=$(realpath "$LAUNCHERPATH")
else
    LAUNCHERPATH=$(realpath "${BASH_SOURCE[0]}")
fi
LAUNCHERDIR="$(dirname $LAUNCHERPATH)"



print-global-uninstall-completion-banner () {
    echo ""
    echo "$BOLD:: Uninstallation complete ::$NORM"
    echo "Kura5 has been deleted from $LAUNCHERDIR"
    echo "It should shortly disappear from the list of installed application"
    echo "Desktop entries, manual pages and the like have also been deleted"
    echo "If You had any issues, please let us know in the project's Discord server"
    exit 0
}

start-global-kura5-uninstall () {
    echo "$BOLD Uninstalling Kura5...$NORM"
    echo "$BOLD:: Removing system integration...$NORM"
    rm -v -f /usr/local/bin/kura5
    rm -v -f /etc/apparmor.d/tunables/kura5
    rm -v -f /etc/apparmor.d/opt.kura5.kura5
    rm -v -f /usr/share/applications/kura5.desktop
    rm -v -f /usr/share/man/man6/kura5.6.gz
    rm -v -f /usr/share/pixmaps/Kura5BOTU.png
    rmdir -v -p --ignore-fail-on-non-empty /etc/apparmor.d/tunables
    rmdir -v -p --ignore-fail-on-non-empty /usr/share/applications
    rmdir -v -p --ignore-fail-on-non-empty /usr/share/man/man6
    rmdir -v -p --ignore-fail-on-non-empty /usr/share/pixmaps
    echo "$BOLD:: Removing the game files...$NORM"
    rm -v -r -f --preserve-root "$LAUNCHERDIR"
    echo " Game files cleared"
    echo " System integration files cleared"
}

confirm-global-uninstall () {
    echo "$BOLD:: Uninstallation requested ::$NORM"
    echo "Confirming deletion of all installed files in /opt/kura5"
    echo -n "Uninstall Kura5 from the system? (y/N): "
    read UNINSTALL
    if [ "$UNINSTALL" == "y" ]; then
        echo "Confirmation received"
        start-global-kura5-uninstall
    else
        echo "Did not receive confirmation"
        echo "Aborting uninstallation"
        exit 0
    fi
}

# 'main' starts here
if [ $(id -u) != "0" ]; then
    echo "Kura5 seems to be installed system-wide"
    echo "As such, only root may run the uninstaller"
    echo "Invoke 'kura5 -unistall' with 'sudo' to run this uninstaller"
    exit 1
else
    confirm-global-uninstall
    print-global-uninstall-completion-banner
fi
