#!/usr/bin/env bash
# Author: EarthlySkies <earthlyskies@protonmail.ch>
# Generic Linux install script for Kura5
# A part of the Kura5 project's Linux integration suite

# Text formatting
BOLD=$(tput bold)
NORM=$(tput sgr0)

# Default installation locations
GLOBALINSTALL="/opt/kura5"
LOCALDATA="$HOME/.local"
LOCALINSTALL="$LOCALDATA/share/Kura5"

print-installer-intro-banner ()  {
    echo "Kura5 universal Linux installer by EarthlySkies"
}

check-home-is-set () {
    if [ "$HOME" == "" ]; then
        echo "\$HOME appears to be unset"
        echo "The installation cannot continue without it"
        echo "Set the \$HOME variable and try the install again"
        exit 1
    fi
}

did-not-find-required-file () {
    echo "Did not find the required file: '$1'"
    echo "Cannot continue the installation without it"
    echo "Do not move, rename or delete the files before installing"
    echo "Re-extracting the archive and trying again should fix the issue"
    exit 2
}

check-presense-of-file () {
    if [ -f ./"$1" ]; then
        return
    else
        [ -f ./Integrations/"$1" ] || did-not-find-required-file "$1"
    fi
}

check-presense-of-all-files () {
    # We don't check for AppArmor profiles since they aren't necessary
    echo "$BOLD:: Verifying that all files for the install are present...$NORM"
    check-presense-of-file "Kura5.x86_64"
    check-presense-of-file "kura5-launcher"
    check-presense-of-file "global-install"
    check-presense-of-file "global-uninstall"
    check-presense-of-file "local-install"
    check-presense-of-file "local-uninstall"
    check-presense-of-file "kura5-manual-page"
    check-presense-of-file "kura5-desktop-icon"
    check-presense-of-file "kura5-desktop-entry"
    echo " All necessary files were found"
}

cannot-write-to-rootfs () {
    echo "$BOLD Could not write to path$NORM '$1'$BOLD even with root privileges$NORM"
    echo "This is likely caused by an immutable root filesystem"
    echo "Cannot proceed with the global installation. Aborting"
    exit 5
}

test-write-to-dir () {
    if [ ! -d "$1" ]; then
        mkdir -p "$1" \
          && rmdir -p --ignore-fail-on-non-empty "$1" \
          || cannot-write-to-rootfs "$1"
    else
        touch "$1" \
          || cannot-write-to-rootfs "$1"
    fi
}

run-rootfs-write-tests () {
    if [ $(id -u) == "0" ]; then
        echo "$BOLD:: Trying to cover for a possibly immutable root filesystem...$NORM"
        test-write-to-dir "$GLOBALINSTALL/Kura5_Data"
        test-write-to-dir "/etc/apparmor.d/tunables"
        test-write-to-dir "/usr/local/bin"
        test-write-to-dir "/usr/share/applications"
        test-write-to-dir "/usr/share/man/man6"
        test-write-to-dir "/usr/share/pixmaps"
        echo " Necessary write-access to the root filesystem should be available"
    fi
}

install-path-taken () {
    echo "Files were found in the target installation directory: $1"
    echo "This path will be$BOLD WIPED$NORM during the installation process"
    echo "If You decide to continue, make sure there are no important files there"
}

install-path-is-available () {
    echo " Install path is free and ready to use"
}

check-install-path-availability () {
    echo "$BOLD:: Checking install path availability...$NORM"
    if [ $(id -u) == "0" ]; then
        [ ! -d "$GLOBALINSTALL" ] \
          && install-path-is-available \
          || install-path-taken "$GLOBALINSTALL"
    else
        [ ! -d "$LOCALINSTALL" ] \
          && install-path-is-available \
          || install-path-taken "$LOCALINSTALL"
    fi
}

ask-for-install-confirmation () {
    echo "$BOLD:: Ready to install$NORM"
    if [ $(id -u) == "0" ]; then
        echo "Detected current user as root. Installing Kura5 for all users"
        echo "Installing to $GLOBALINSTALL"
        [ -f ./Integrations/global-install ] && . ./Integrations/global-install
    else
        echo "Detected current user as '$USER' (unprivileged)"
        echo "Installing Kura5 only for the current user"
        echo "Installing to $LOCALINSTALL"
        [ -f ./Integrations/local-install ] && . ./Integrations/local-install
    fi
    echo "This directory will be$BOLD WIPED$NORM during the install"
    echo -n "Start the installation? (y/N): "
    read STARTINSTALL
    if [ "$STARTINSTALL" == "y" ]; then
        [[ $(id -u) == "0" ]] \
          && start-global-kura5-install \
          || start-local-kura5-install
    else
        echo "Did not receive an affirmative response"
        echo "Aborting the installation"
        echo "No files have been changed"
        exit 0
    fi
}

main () {
    print-installer-intro-banner
    check-home-is-set
    check-presense-of-all-files
    check-install-path-availability
    run-rootfs-write-tests
    ask-for-install-confirmation
}

main
