#!/usr/bin/env bash
# A small shell script wrapper for Kura5
# Usually placed in /usr/bin or /usr/local/bin
# Allows Kura5 to integrate into $PATH and the desktop

# If different, modify the installation location here
KURA5EXECUTABLE=(/opt/kura5/kura5)

# These directories should be created so we may access them in the sandbox
/usr/bin/mkdir --parents ~/.config/unity3d/Kura5/Kura5BOTU > /dev/null 2>&1

# Using "-single-instance" has been determined as a sane default
"$KURA5EXECUTABLE" -single-instance "$@"
